name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  AZURE_WEBAPP_NAME: ad-taskmanagement-demo
  AZURE_WEBAPI_PACKAGE_PATH: "./publish"
  AZURE_WEBUI_PACKAGE_PATH: "./publish/wwwroot"
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies for backend
        run: dotnet restore ./TaskManagementApp.WebAPI/TaskManagementApp.WebAPI.csproj

      - name: Build
        run: dotnet build --configuration Release --no-restore ./TaskManagementApp.WebAPI/TaskManagementApp.WebAPI.csproj

      - name: Test
        run: dotnet test ./TaskManagementApp.UnitTests/TaskManagementApp.UnitTests.csproj --no-build --filter "Category!=Exclude" --verbosity normal

      - name: Publish backend
        run: dotnet publish ./TaskManagementApp.WebAPI/TaskManagementApp.WebAPI.csproj --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

      - name: Install dependencies for frontend
        run: npm install --prefix ./ClientApp
        working-directory: ./TaskManagementApp.UI

      - name: Build
        run: npm run build --if-present --prefix ./ClientApp
        working-directory: ./TaskManagementApp.UI

      - name: Copy frontend build to backend publish folder
        run: cp -r ./ClientApp/build/* ${{ env.AZURE_WEBUI_PACKAGE_PATH }}       
